# Generated by Django 2.2.6 on 2019-11-17 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20191103_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=15)),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
