# Generated by Django 2.2.6 on 2019-12-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_telegramlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_session', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventsInDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Day')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='events',
            field=models.ManyToManyField(through='camp.EventsInDay', to='camp.Event'),
        ),
        migrations.AddField(
            model_name='day',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Plan'),
        ),
    ]
