# Generated by Django 2.2.6 on 2019-12-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_auto_20191204_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='c_session',
            new_name='campsession',
        ),
    ]
